### ISSUE TITLE
App zeigt nur schwarzen Bildschirm

### ISSUE THREAD

**Issue by michaelklose** [jp-fan-app/ios#7]
Hallo, 

die neue Version 2.0.0 zeigt nach dem öffnen nur einen schwarzen Bildschirm.

Was hab ich bisher probiert:
- App beendet / neugestartet
- App  deinstalliert / neuinstalliert
- Iphone neugestartet

Problem besteht auf einem Iphone Xs mit IOS 13.3

**Comment by cpageler93** [comment]
Hi @michaelklose,
Leider sehe ich das Issue jetzt erst, Sorry!
Besteht das Problem weiterhin? In den ersten Tagen nach dem Release gab es ein paar Serverprobleme aufgrund der hohen Zugriffe. Dies sollte jetzt aber gelöst sein. 

Liebe Grüße,
Christoph

**Comment by michaelklose** [comment]
Mittlerweile funktioniert alles. Danke für diese super App. Weiter so!

Gruß
Michael
